linters:
    flake8:
    eslint:
        config: 
    csslint:
        ignore: 'box-model,ids'
    stylelint:
        config: 'stylelint.config.js'
        
files:
    ignore:
        - 'src/generated/*'
        - 'webroot/bower_components/*'