linters:
    flake8:
    eslint:
       
    csslint:
        config: './stylelint.config'

files:
    ignore:
        - 'src/generated/*'
        - 'webroot/bower_components/*'
fixers:
    enable: true