linters:
    flake8:
    eslint:
        config: './eslint.config'
    csslint:
         ignore:
            - 'box-model,ids'
            - 'h2 , h3'
            - 'order-alphabetical'

files:
    ignore:
        - 'src/generated/*'
        - 'webroot/bower_components/*'
        - 'box-model,ids'
        - 'h2 , h3'
        - 'order-alphabetical'